/* eslint-disable */
// V11 — api/observation-memory.js
// AI's persistent qualitative notes per instrument. Survives between cron calls.
// AI writes them, future AI calls read them, expire if not refreshed.
//
// Storage: v11:obs:{sym}  → { ts, observations: [...] }
//
// Each observation:
//   {
//     id: string,             // generated by AI, used for refresh/invalidate
//     text: string,           // the observation itself
//     direction: 'LONG'|'SHORT'|'NEUTRAL',
//     watchLevel: number,     // price level being watched (optional)
//     invalidatesAt: number,  // price beyond which observation is dead (optional)
//     refreshUntil: number,   // ts after which observation auto-expires
//     createdAt: number,
//   }

const { getRedis, normSym, safeParse } = require('./_lib');

const MAX_OBS_PER_SYMBOL = 5;
const DEFAULT_REFRESH_HOURS = 4;

// =================================================================
// READ — used by AI prompt
// =================================================================
async function readObservations(sym) {
  const r = getRedis();
  if (!r) return [];
  const raw = await r.get('v11:obs:' + normSym(sym)).catch(() => null);
  const parsed = safeParse(raw);
  if (!parsed || !Array.isArray(parsed.observations)) return [];
  // Filter expired
  const now = Date.now();
  return parsed.observations.filter(o => o.refreshUntil > now);
}

// =================================================================
// WRITE — used when AI returns observations in its decision
// =================================================================
// AI provides an array of observation objects in its decision JSON. We merge them
// with existing: new IDs are added, existing IDs have their refreshUntil bumped,
// missing IDs from previous list expire naturally.
async function writeObservations(sym, newObs) {
  if (!Array.isArray(newObs) || newObs.length === 0) return { written: 0 };
  const r = getRedis();
  if (!r) return { written: 0 };

  const existing = await readObservations(sym);
  const byId = new Map();
  for (const o of existing) byId.set(o.id, o);

  const now = Date.now();
  let written = 0;
  for (const obs of newObs) {
    if (!obs || !obs.id || typeof obs.text !== 'string') continue;
    const refreshHours = obs.refreshHours || DEFAULT_REFRESH_HOURS;
    const merged = {
      id: String(obs.id).slice(0, 64),
      text: String(obs.text).slice(0, 300),
      direction: obs.direction || 'NEUTRAL',
      watchLevel: typeof obs.watchLevel === 'number' ? obs.watchLevel : null,
      invalidatesAt: typeof obs.invalidatesAt === 'number' ? obs.invalidatesAt : null,
      refreshUntil: now + refreshHours * 60 * 60 * 1000,
      createdAt: byId.has(obs.id) ? byId.get(obs.id).createdAt : now,
    };
    byId.set(merged.id, merged);
    written++;
  }

  // Sort by createdAt desc, cap at MAX_OBS_PER_SYMBOL
  const list = Array.from(byId.values())
    .sort((a, b) => b.createdAt - a.createdAt)
    .slice(0, MAX_OBS_PER_SYMBOL);

  await r.set('v11:obs:' + normSym(sym), JSON.stringify({
    ts: now,
    observations: list,
  }), { ex: 24 * 60 * 60 }).catch(() => {});  // 24h hard TTL on the key

  return { written, total: list.length };
}

// =================================================================
// CLEAR — manual override (from a debug endpoint)
// =================================================================
async function clearObservations(sym) {
  const r = getRedis();
  if (!r) return;
  await r.del('v11:obs:' + normSym(sym)).catch(() => {});
}

// =================================================================
// INVALIDATE — check if any observations have been broken by current price
// Called by setup-detector or AI before reading.
// =================================================================
async function invalidateBrokenObservations(sym, currentPrice) {
  if (!currentPrice || !isFinite(currentPrice)) return;
  const r = getRedis();
  if (!r) return;
  const obs = await readObservations(sym);
  if (obs.length === 0) return;
  const stillValid = obs.filter(o => {
    if (o.invalidatesAt == null) return true;
    if (o.direction === 'LONG'  && currentPrice <= o.invalidatesAt) return false;
    if (o.direction === 'SHORT' && currentPrice >= o.invalidatesAt) return false;
    return true;
  });
  if (stillValid.length !== obs.length) {
    await r.set('v11:obs:' + normSym(sym), JSON.stringify({
      ts: Date.now(),
      observations: stillValid,
    }), { ex: 24 * 60 * 60 }).catch(() => {});
  }
}

// =================================================================
// HTTP handler — for inspection/debugging
// =================================================================
module.exports = async (req, res) => {
  const sym = String(req.query.symbol || '').toUpperCase();
  if (!sym) return res.status(400).json({ error: 'symbol required' });

  const action = String(req.query.action || 'read');
  if (action === 'clear') {
    await clearObservations(sym);
    return res.status(200).json({ symbol: sym, cleared: true });
  }
  // default: read
  const observations = await readObservations(sym);
  return res.status(200).json({ symbol: sym, count: observations.length, observations });
};

module.exports.readObservations           = readObservations;
module.exports.writeObservations          = writeObservations;
module.exports.clearObservations          = clearObservations;
module.exports.invalidateBrokenObservations = invalidateBrokenObservations;